name: classification-xai-demo

services:
  demo-api:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.backend
    image: demo-api:latest
    container_name: demo-api
    environment:
      - BACKEND_PORT=5000
    ports:
      - "${BACKEND_PORT}:5000"
    restart: always

  demo-web:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.frontend
    image: demo-web:latest
    container_name: demo-web
    environment:
      - PREDICTION_BACKEND_ENDPOINT=http://demo-api:5000/predict
      - LOCAL_XAI_ENDPOINT=http://demo-api:5000/xai/local
      - GLOBAL_XAI_ENDPOINT=http://demo-api:5000/xai/global
      - DATASET_SELECTION_ENDPOINT=http://demo-api:5000/dataset/select
      - DATASET_CURRENT_ENDPOINT=http://demo-api:5000/dataset/current
    ports:
      - "${STREAMLIT_PORT}:8501"
    depends_on:
      - demo-api
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=error
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../monitoring/grafana-provisioning:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  grafana-storage:

